name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 1233 -H 146.83.198.35 >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -p 1233 usuario@146.83.198.35 << 'EOF'
            cd /ruta/del/proyecto
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
